ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER english_dictionary IDENTIFIED BY english_dictionary;
GRANT RESOURCE, CONNECT TO english_dictionary;
ALTER USER english_dictionary DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;