SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE EMP_NO LIKE '7%'
AND SUBSTR(EMP_NO, 8 , 1) = '2'
AND EMP_NAME LIKE '전%';

SELECT EMP_ID, EMP_NAME, JOB_NAME, DEPT_TITLE
FROM EMPLOYEE
-- NATURAL JOIN JOB
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
WHERE EMP_NAME LIKE '%형%';

SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_TITLE IN ('해외영업1부', '해외영업2부');
/*
WHERE DEPT_TITLE LIKE '%1부'
OR DEPT_TITLE LIKE '%2부';
 * */

SELECT EMP_NAME, BONUS, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
LEFT JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
WHERE BONUS IS NOT NULL;
-- INNER JOIN 하면 하동운이 안 나옴 (DEPT_TITLE, LOCAL_NAME 이 NULL 이라서)

SELECT EMP_NAME, JOB_NAME, DEPT_TITLE, LOCAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN JOB USING (JOB_CODE)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE);
-- WHERE DEPT_CODE IS NOT NULL; (INNER JOIN 사용해서 NULL이면 안 나옴)

-- SELECT EMP_NAME, JOB_NAME, SALARY, (SALARY + SALARY*BONUS) * 12
-- SELECT EMP_NAME, JOB_NAME, SALARY, (SALARY * 12) + SALARY*BONUS
SELECT EMP_NAME, JOB_NAME, SALARY, SALARY *( 1 + NVL(BONUS, 0) ) * 12
FROM EMPLOYEE
NATURAL JOIN JOB
NATURAL JOIN SAL_GRADE
WHERE SALARY > MIN_SAL;

SELECT EMP_NAME, DEPT_TITLE, LOCAL_NAME, NATIONAL_NAME
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
JOIN LOCATION ON (LOCATION_ID = LOCAL_CODE)
JOIN "NATIONAL" USING (NATIONAL_CODE)
WHERE NATIONAL_NAME IN ('한국', '일본');
-- WHERE NATIONAL_CODE IN ('KO', 'JP');

SELECT E1.EMP_NAME 사원명, E1.DEPT_CODE, E2.EMP_NAME 동료이름
FROM EMPLOYEE E1
JOIN EMPLOYEE E2 ON (E1.DEPT_CODE = E2.DEPT_CODE)
WHERE E1.EMP_NAME != E2.EMP_NAME
ORDER BY 사원명;

SELECT EMP_NAME, JOB_NAME, SALARY
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE BONUS IS NULL
AND JOB_CODE IN ('J4', 'J7');

-- 수정