SELECT EMP_ID, EMP_NAME, PHONE, TO_CHAR(HIRE_DATE, 'YY/MM/DD'), DEPT_TITLE
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE
                   FROM EMPLOYEE
                   WHERE EMP_NAME = '전지연')
AND EMP_NAME != '전지연';

SELECT EMP_ID, EMP_NAME, PHONE, SALARY, JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
WHERE SALARY = (SELECT MAX(SALARY)
								FROM EMPLOYEE
								WHERE TO_CHAR(HIRE_DATE, 'YYYY-MM-DD') >= '2000-01-01');
								
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, DEPT_TITLE, JOB_NAME
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
															 FROM EMPLOYEE
															 WHERE EMP_NAME = '노옹철')
AND EMP_NAME != '노옹철';

SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE, JOB_CODE) = (SELECT DEPT_CODE, JOB_CODE
															 FROM EMPLOYEE
															 WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000);

SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) = (SELECT DEPT_CODE, MANAGER_ID
																 FROM EMPLOYEE
																 WHERE EMP_NO LIKE '77%'
																 AND SUBSTR(EMP_NO, 8, 1) = '2');

-- 6번 7명
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
-- WHERE ENT_YN = 'N'
WHERE HIRE_DATE IN (SELECT MIN(HIRE_DATE)
                  FROM EMPLOYEE
                  LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
                  WHERE ENT_YN = 'N'
                  GROUP BY DEPT_CODE)
ORDER BY HIRE_DATE;

-- 6번 
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE HIRE_DATE IN (SELECT MIN(HIRE_DATE)
                  FROM EMPLOYEE
                  WHERE ENT_YN != 'Y'
                  GROUP BY DEPT_CODE)
ORDER BY HIRE_DATE;

-- 6번

SELECT MIN(HIRE_DATE)
FROM EMPLOYEE
WHERE ENT_YN != 'Y'
AND DEPT_CODE = 'D1'; 


SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE MAIN
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE HIRE_DATE = (
							SELECT MIN(HIRE_DATE)
							FROM EMPLOYEE SUB
							WHERE ENT_YN != 'Y'
							AND MAIN.DEPT_CODE = SUB.DEPT_CODE
							OR (MAIN.DEPT_CODE IS NULL AND SUB.DEPT_CODE IS NULL) 
						)
ORDER BY HIRE_DATE;

--IS NULL
--IS NOT NULL

/*
SELECT EMP_ID, EMP_NAME, NVL(DEPT_TITLE, '소속없음'), JOB_NAME, HIRE_DATE
FROM EMPLOYEE MAIN
NATURAL JOIN JOB
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
-- WHERE ENT_YN = 'N'
AND HIRE_DATE IN (SELECT MIN(HIRE_DATE)
                  FROM EMPLOYEE SUB
                  WHERE MAIN.DEPT_CODE = SUB.DEPT_CODE
                  AND (ENT_YN = 'N'
                  OR MAIN.DEPT_CODE IS NULL)
                  AND MAIN.DEPT_CODE = SUB.DEPT_CODE
                  AND (ENT_YN = 'N'
                  OR SUB.DEPT_CODE IS NULL))
ORDER BY HIRE_DATE;
*/
