CREATE TABLE MAJOR (
		MAJOR_NO NUMBER PRIMARY KEY,
		MAJOR_NM VARCHAR2(100) NOT NULL
);

COMMENT ON COLUMN MAJOR.MAJOR_NO IS '학과번호';
COMMENT ON COLUMN MAJOR.MAJOR_NM IS '학과명';

CREATE TABLE STUDENT (
		STUDENT_ID NUMBER PRIMARY KEY,
		STUDENT_NAME VARCHAR2(20) NOT NULL,
		GENDER VARCHAR2(3) CHECK(GENDER IN ('남', '여')),
		BIRTH DATE,
		MAJOR_NO NUMBER REFERENCES MAJOR ON DELETE SET NULL
);

COMMENT ON COLUMN STUDENT.STUDENT_ID IS '학번';
COMMENT ON COLUMN STUDENT.STUDENT_NAME IS '이름';
COMMENT ON COLUMN STUDENT.GENDER IS '성별';
COMMENT ON COLUMN STUDENT.BIRTH IS '생년월일';
COMMENT ON COLUMN STUDENT.MAJOR_NO IS '전공학과번호';

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

INSERT INTO MAJOR VALUES (1, '국어국문학과');
INSERT INTO MAJOR VALUES (2, '영어영문학과');
INSERT INTO MAJOR VALUES (3, '사학과');
INSERT INTO MAJOR VALUES (4, '철학과');
INSERT INTO MAJOR VALUES (5, '법학과');

SELECT * FROM MAJOR;

INSERT INTO STUDENT VALUES (1, '서가람', '여', '19950719', 1);
INSERT INTO STUDENT VALUES (2, '남가영', '여', '19860510', 2);
INSERT INTO STUDENT VALUES (3, '주강민', '남', '19840808', 3);
INSERT INTO STUDENT VALUES (4, '손건영', '남', '19840718', 4);
INSERT INTO STUDENT VALUES (5, '박건우', '남', '19850326', 5);

SELECT * FROM STUDENT;

ALTER TABLE MAJOR RENAME COLUMN MAJOR_NM TO MAJOR_NAME;