CREATE TABLE TODO (
	"TODO_NO" NUMBER CONSTRAINT "PK_TODO" PRIMARY KEY, -- 기본키 NUMBER
	TODO_TITLE NVARCHAR2(50), -- 제목
	TODO_CONTENT NVARCHAR2(300), -- 내용 CLOB 이든지 NVARCHAR2
	TODO_REQUEST_MEMBER_NO NUMBER NOT NULL, -- 요청한 놈 MEMBER테이블 기본키로서 이 컬럼은 외래키로 설정함. 1번 페이지 나눌 때 사용
	COMPLETE_CONDITION NUMBER NOT NULL, -- 완료조건 한명만 해도되면 1, 모두 다 해야 완료되는 조건이면 2, 1인 경우 한명이 완료 누르면 완료된 걸로 넘어가게
	TODO_DATE DATE DEFAULT SYSDATE, -- 요청한 날짜를 기록함. 조회조건 중 등록순을 위함.
	DEADLINE DATE, -- 기한을 나타냄 DATE
	TODO_COMPLETE CHAR(1) DEFAULT 'N' NOT NULL, -- 요청 받은 사람이 완료하기를 눌렀을 때 상태 변화를 나타내 줌 3번 페이지 나눌 때 사용
	TODO_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL
);

CREATE TABLE "TODO_FILE" (
	"TODO_FILE_NO"	NUMBER		NOT NULL,
	"TODO_FILE_PATH"	VARCHAR2(200)		NOT NULL,
	"TODO_FILE_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"TODO_FILE_RENAME"	NVARCHAR2(50)		NOT NULL,
	"TODO_FILE_ORDER"	NUMBER		NULL,
	"TODO_NO"	NUMBER		NOT NULL
);

CREATE TABLE "LOGO_FILE" (
	"FILE_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NOT NULL,
	"FILE_ORIGINAL_NAME"	VARCHAR2(300)		NOT NULL,
	"FILE_RENAME"	VARCHAR2(100)		NOT NULL,
	"FILE_UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COM_NO"	NUMBER		NOT NULL
);

ALTER TABLE "LOGO_FILE" ADD CONSTRAINT "PK_LOGO_FILE" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "LOGO_FILE" ADD CONSTRAINT "FK_COMPANY_TO_LOGO_FILE" FOREIGN KEY (
	"COM_NO"
)
REFERENCES "COMPANY" (
	"COM_NO"
);

CREATE SEQUENCE SEQ_LOGO_FILE NOCACHE;

COMMIT;

ALTER TABLE "TODO_FILE" ADD CONSTRAINT "PK_TODO_FILE" PRIMARY KEY (
	"TODO_FILE_NO"
);

ALTER TABLE "TODO_FILE" ADD CONSTRAINT "FK_TODO_TO_TODO_FILE" FOREIGN KEY (
	"TODO_NO"
)
REFERENCES "TODO" (
	"TODO_NO"
);

CREATE SEQUENCE SEQ_TODO_NO NOCACHE;
CREATE SEQUENCE SEQ_TODO_FILE_NO NOCACHE;

COMMIT;

SELECT * FROM TODO;
SELECT * FROM TODO_FILE;

-----------------------------------------------------------------------------------

SELECT * FROM EMPLOYEE;
SELECT * FROM COMPANY;

SELECT * FROM LOGO_FILE;