SELECT * FROM EMPLOYEE;

SELECT EMP_NAME, NVL(DEPT_TITLE, '부서없음') AS DEPT_TITLE, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE NVL(DEPT_TITLE, '부서없음') = '부서없음';

-- 해당 직급에서 입력 받은 급여보다 많이 받는
-- 사원의 이름, 직급명, 급여, 연봉을 조회하여 출력
SELECT EMP_NAME, JOB_NAME, SALARY, SALARY*12 연봉
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE JOB_NAME = '부사장'
AND SALARY > 3000000;

SELECT EMP_NAME 이름,
TO_CHAR(HIRE_DATE, 'YYYY"년" MM"월" DD"일"') 입사일,
DECODE( SUBSTR(EMP_NO, 8, 1), '1', 'M', '2', 'F' ) 성별 
FROM EMPLOYEE
WHERE HIRE_DATE < TO_DATE('2000-01-01');

SELECT EMP_ID, EMP_NAME, PHONE, TO_CHAR(HIRE_DATE, 'YYYY-MM-DD'), DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
WHERE DEPT_CODE = (SELECT DEPT_CODE
									 FROM EMPLOYEE
									 WHERE EMP_NAME = '전지연');