-- 로그인
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER,
			TO_CHAR(ENROLL_DT, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DT
-- 데이터 포맷이 아님 단순 문자열로 표시
FROM "MEMBER"
WHERE MEMBER_ID = 'user01'
AND MEMBER_PW = 'pass01'
AND UNREGISTER_FL = 'N';
-- 탈퇴 안한 사람만

-- 아이디 중복 검사
SELECT COUNT(*)
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
AND MEMBER_ID = 'user01';
-- 중복이 있으면 1 중복이 없으면 0

SELECT * FROM "MEMBER";

SELECT MEMBER_ID, MEMBER_NM, DECODE(MEMBER_GENDER, 'M', '남', '여') 성별
FROM "MEMBER"
WHERE UNREGISTER_FL = 'N'
ORDER BY MEMBER_NO DESC;