-- Promotion Site
-- 회원 테이블 생성
CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEM_ID"	NVARCHAR2(300)		NOT NULL,
	"MEM_PW"	NVARCHAR2(300)		NOT NULL,
	"MEM_NICKNAME"	NVARCHAR2(300)		NOT NULL,
	"MEM_TEL"	NVARCHAR2(11)		NOT NULL,
	"MEM_PROFILE"	NVARCHAR2(300)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEM_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 식별키';

COMMENT ON COLUMN "MEMBER"."MEM_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEM_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEM_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEM_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."MEM_PROFILE" IS '회원 프로필';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEM_DEL_FL" IS '회원 탈퇴 여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '1: 일반회원 2: 관리자';

COMMIT;