-- Promotion Site
-- 회원 테이블 생성
CREATE TABLE "MEMBER"(
	"MEMBER_NO"       NUMBER CONSTRAINT "MEMBER_PK" PRIMARY KEY,
	"MEMBER_EMAIL" 		NVARCHAR2(50)  NOT NULL,
	"MEMBER_PW"				NVARCHAR2(100) NOT NULL,
	"MEMBER_NICKNAME" NVARCHAR2(10)  NOT NULL,
	"MEMBER_TEL"			CHAR(11)       NOT NULL,
	"PROFILE_IMG"			VARCHAR2(300),
	"ENROLL_DATE"			DATE           DEFAULT SYSDATE NOT NULL,
	"MEMBER_DEL_FL"		CHAR(1) 			 DEFAULT 'N'
									  CHECK("MEMBER_DEL_FL" IN ('Y', 'N') ),
	"AUTHORITY"				NUMBER 			   DEFAULT 1
										CHECK("AUTHORITY" IN (1, 2) )
);

-- 회원 번호 시퀀스 만들기
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 식별키';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원 닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '회원 탈퇴 여부';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '1: 일반회원 2: 관리자';

COMMIT;

SELECT * FROM MEMBER;

CREATE TABLE "EMAIL_AUTH_KEY"(
	"KEY_NO"    NUMBER PRIMARY KEY,
	"EMAIL"	    NVARCHAR2(50) NOT NULL,
	"AUTH_KEY"  CHAR(6)	NOT NULL,
	"CREATE_TIME" DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN "EMAIL_AUTH_KEY"."KEY_NO"      IS '인증키 구분 번호(시퀀스)';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."EMAIL"       IS '인증 이메일';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."AUTH_KEY"    IS '인증 번호';
COMMENT ON COLUMN "EMAIL_AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

CREATE SEQUENCE SEQ_KEY_NO NOCACHE; -- 인증키 구분 번호 시퀀스

SELECT * FROM "EMAIL_AUTH_KEY";

COMMIT;

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW,
	MEMBER_NICKNAME, MEMBER_TEL, PROFILE_IMG,
	ENROLL_DATE, AUTHORITY
FROM "MEMBER"
WHERE MEMBER_DEL_FL = 'N'