SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
-- WHERE LENGTH (PROFESSOR_NAME) != 3;
WHERE PROFESSOR_NAME NOT LIKE '___';

SELECT PROFESSOR_NAME 교수이름,
--		 '2024' - TO_CHAR(EXTRACT ( YEAR FROM (TO_DATE( SUBSTR (PROFESSOR_SSN , 1, INSTR(PROFESSOR_SSN, '-') -1), 'RRRRMMDD')))) 나이
--		 TO_CHAR(	EXTRACT ( YEAR FROM (TO_DATE( SUBSTR (PROFESSOR_SSN , 1, INSTR(PROFESSOR_SSN, '-') -1), 'RRMMDD')))) 나이
			 '2024' - ('19'  || SUBSTR (PROFESSOR_SSN , 1, 2)) 나이
FROM TB_PROFESSOR
WHERE SUBSTR (PROFESSOR_SSN, 8, 1) = '1'
ORDER BY '2024' - ('19'  || SUBSTR (PROFESSOR_SSN , 1, 2));

SELECT PROFESSOR_NAME 교수이름,
FLOOR( MONTHS_BETWEEN(SYSDATE, TO_DATE( '19' || SUBSTR (PROFESSOR_SSN, 1, 6), 'YYYYMMDD' )) / 12) 나이 
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8 , 1) = '1'
ORDER BY 나이;

SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR( EXTRACT (YEAR FROM ENTRANCE_DATE) ) - ('19' || SUBSTR (STUDENT_SSN, 1, 2)) > 19;

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -- 입학년도 (2002)
- EXTRACT(YEAR FROM TO_DATE ('19' || SUBSTR (STUDENT_SSN, 1, 6), 'YYYYMMDD' )) > 19; -- 학생출생년도(1988)
-- 입학일에서 출생년도 빼면 입학한 나이가 나옴. 얘가 19보다 크다면 재수생

-- 'DAY' : 월요일 'DY' : 월 'D' : 2
-- 1 : 일요일
-- 2 : 월요일
-- 3 : 화요일
-- 4 : 수요일
-- 5 : 목요일
-- 6 : 금요일
-- 7 : 토요일
SELECT TO_CHAR(TO_DATE('20201225'), 'DAY') "2020년 크리스마스" FROM DUAL;

SELECT TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'),
       TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;
-- YY는 다 20년
-- RR 은 50 이전 19 50 이후 20

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR( STUDENT_NO, 1 , 1) != 'A';

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';

SELECT ROUND( AVG(POINT) , 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND( AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

SELECT DEPARTMENT_NO "학과코드명",
SUM(DECODE(ABSENCE_YN, 'Y' , 1, 0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

SELECT STUDENT_NAME "동일이름" , COUNT(*) "동명인 수" 
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY STUDENT_NAME;

SELECT NVL( SUBSTR(TERM_NO, 1, 4), ' ' )년도, NVL( SUBSTR(TERM_NO, 5, 2), ' ' ) 학기, ROUND( AVG(POINT), 1 ) 평점
FROM TB_GRADE
WHERE STUDENT_NO  = 'A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2));