-- 버스 예약 시스템

-- 버스(BUS) 테이블
CREATE TABLE BUS(
	BUS_NO NUMBER CONSTRAINT BUS_PK PRIMARY KEY,
	-- CONSTRAINT (제약 조건) 뒤에 제약 조건명
	-- PRIMARY KEY : NOT NULL + UNIQUE
	BUS_DEPARTURES VARCHAR2(30) NOT NULL,
	-- 출발지 NULL 이면 안됨
	BUS_ARRIVALS VARCHAR2(30) NOT NULL,
	-- 도착지 NULL 이면 안됨
	
);