SELECT COUNT(*)
FROM RESERVE_PERSON
WHERE PHONE = '010111111111';

INSERT INTO RESERVE_PERSON(NAME, PHONE)
VALUES(?, ?);

SELECT NAME, PHONE, BUS_DEPARTURES, BUS_ARRIVALS,
BUS_DEPARTURE_TIME, BUS_NO, SEAT_NO
FROM RESERVE_PERSON
WHERE PHONE = ?;

SELECT BUS_NO, BUS_DEPARTURES, BUS_ARRIVALS,
BUS_DEPARTURE_TIME, BUS_ARRIVAL_TIME
FROM BUS;

SELECT BUS_NO, COUNT(*)
FROM BUS_SEAT
WHERE SEAT_RESERVATION = 'N'
GROUP BY BUS_NO;

-- 버스 번호 입력 받아서 남은 좌석 출력
SELECT SEAT_NO
FROM BUS_SEAT
WHERE SEAT_RESERVATION = 'N'
AND BUS_NO = 5001;

-- 버스 번호 받아서 출발지, 도착지, 출발시간 출력
SELECT BUS_DEPARTURES, BUS_ARRIVALS, BUS_DEPARTURE_TIME
FROM BUS
WHERE BUS_NO = '5000';

UPDATE RESERVE_PERSON R SET
R.BUS_DEPARTURES = (SELECT B.BUS_DEPARTURES
										FROM BUS B
										WHERE B.BUS_NO = '5000'),
R.BUS_ARRIVALS = (SELECT B.BUS_ARRIVALS
									FROM BUS B
									WHERE B.BUS_NO = '5000'),
R.BUS_DEPARTURE_TIME  = (SELECT B.BUS_DEPARTURE_TIME
												FROM BUS B
												WHERE B.BUS_NO = '5000'),
R.BUS_NO = '5000',
R.SEAT_NO = 1
WHERE R.PHONE = '01011111111';

COMMIT;

UPDATE BUS_SEAT SET
SEAT_RESERVATION = 'Y'
WHERE SEAT_RESERVATION = 'N'
AND BUS_NO = 5000
AND SEAT_NO = 20;

ROLLBACK;

-- 전화번호로 예약 정보 조회
SELECT BUS_DEPARTURES, BUS_ARRIVALS, BUS_DEPARTURE_TIME, BUS_NO, SEAT_NO
FROM RESERVE_PERSON
WHERE PHONE = 01011111111;

-- 예약취소
UPDATE RESERVE_PERSON SET
BUS_DEPARTURES = NULL,
BUS_ARRIVALS = NULL,
BUS_DEPARTURE_TIME = NULL,
BUS_NO = NULL,
SEAT_NO = NULL
WHERE PHONE = '01011111111';

ROLLBACK;

SELECT COUNT(*)
FROM BUS_SEAT
WHERE SEAT_RESERVATION = 'Y';