CREATE TABLE FREEBOARD (
	CODE_TYPE	VARCHAR2(2)	NOT NULL,
	NUM	NUMBER	NOT NULL,
	NAME	VARCHAR2(100)	NOT NULL,
	TITLE	VARCHAR2(100)	NOT NULL,
	CONTENT	VARCHAR2(100)	NOT NULL,
	REGDATE	DATE DEFAULT SYSDATE NOT NULL
);

ALTER TABLE FREEBOARD ADD CONSTRAINT PK_FREEBOARD PRIMARY KEY (
	NUM
);

CREATE SEQUENCE SEQ_NUM NOCACHE;

INSERT INTO FREEBOARD VALUES ('01', SEQ_NUM.NEXTVAL, '교육생1', '안녕하세요1', '안녕하세요1', DEFAULT);
INSERT INTO FREEBOARD VALUES ('02', SEQ_NUM.NEXTVAL, '교육생2', '안녕하세요2', '안녕하세요2', DEFAULT);
INSERT INTO FREEBOARD VALUES ('03', SEQ_NUM.NEXTVAL, '교육생3', '안녕하세요3', '안녕하세요3', DEFAULT);
INSERT INTO FREEBOARD VALUES ('01', SEQ_NUM.NEXTVAL, '교육생4', '안녕하세요4', '안녕하세요4', DEFAULT);
INSERT INTO FREEBOARD VALUES ('02', SEQ_NUM.NEXTVAL, '교육생5', '안녕하세요5', '안녕하세요5', DEFAULT);

SELECT * FROM FREEBOARD;

-- 01 자유 02 익명 03 QnA + CODE_TYPE 언더바 문제 해결 (mapper에 작성함)
SELECT CASE WHEN CODE_TYPE = '01' THEN '자유'
	WHEN CODE_TYPE = '02' THEN '익명'
	ELSE 'QnA' END AS CODETYPE, NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE FROM FREEBOARD;
	
-- 다른 함수 한가지
SELECT DECODE(CODE_TYPE, '01', '자유', DECODE(CODE_TYPE, '02', '익명', 'QnA')) AS CODETYPE,
	NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE FROM FREEBOARD;


SELECT CASE WHEN CODE_TYPE = '01' THEN '자유'
	WHEN CODE_TYPE = '02' THEN '익명'
	ELSE 'QnA' END AS CODETYPE, NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE
FROM FREEBOARD
WHERE LOWER(TITLE) LIKE '%자%';

SELECT CASE WHEN CODE_TYPE = '01' THEN '자유'
	WHEN CODE_TYPE = '02' THEN '익명'
	ELSE 'QnA' END AS CODETYPE, NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE
FROM FREEBOARD
WHERE REGDATE BETWEEN TO_DATE('20240101', 'YYYYMMDD') AND TO_DATE('20241107 23:59:59', 'YYYYMMDD HH24:MI:SS');

SELECT CASE WHEN CODE_TYPE = '01' THEN '자유'
	WHEN CODE_TYPE = '02' THEN '익명'
	ELSE 'QnA' END AS CODETYPE, NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE
FROM FREEBOARD
WHERE REGDATE  >= TO_DATE('20240101', 'YYYYMMDD')
	AND REGDATE <= TO_DATE('20241107 23:59:59', 'YYYYMMDD HH24:MI:SS');
	
SELECT CASE WHEN CODE_TYPE = '01' THEN '자유'
	WHEN CODE_TYPE = '02' THEN '익명'
	ELSE 'QnA' END AS CODETYPE, NUM, NAME, TITLE, CONTENT, TO_CHAR(REGDATE , 'YYYY/MM/DD') AS REGDATE
FROM FREEBOARD
WHERE 1=1
AND TO_CHAR(REGDATE, 'YYYYMMDD') BETWEEN '20241101' AND '20241107';

SELECT COUNT(*)
FROM FREEBOARD;

SELECT * FROM FREEBOARD WHERE CODE_TYPE = '02';