CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_EMAIL"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_PW"	NVARCHAR2(50)		NOT NULL,
	"MEMBER_NICKNAME"	NVARCHAR2(10)		NOT NULL,
	"MEMBER_TEL"	CHAR(11)		NULL,
	"MEMBER_ADDRESS"	VARCHAR2(300)		NULL,
	"PROFILE_IMG"	VARCHAR2(150)		NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"AUTHORITY"	NUMBER	DEFAULT 1	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NICKNAME" IS '회원닉네임';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원전화번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDRESS" IS '회원주소';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DATE" IS '회원가입일';

COMMENT ON COLUMN "MEMBER"."MEMBER_DEL_FL" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "MEMBER"."AUTHORITY" IS '권한(1:일반,2:관리자)';

CREATE TABLE "AUTH_KEY" (
	"KEY_NO"	NUMBER		NOT NULL,
	"EMAIL"	NVARCHAR2(50)		NOT NULL,
	"AUTH_KEY"	CHAR(6)		NOT NULL,
	"CREATE_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "AUTH_KEY"."KEY_NO" IS '인증키 구분 번호(시퀀스)(PK)';

COMMENT ON COLUMN "AUTH_KEY"."EMAIL" IS '인증 이메일';

COMMENT ON COLUMN "AUTH_KEY"."AUTH_KEY" IS '인증 번호';

COMMENT ON COLUMN "AUTH_KEY"."CREATE_TIME" IS '인증 번호 생성 시간';

COMMENT ON COLUMN "AUTH_KEY"."MEMBER_NO" IS '회원번호(PK)';

CREATE TABLE "LECTURE_DAYS" (
	"LECTURE_DAYS_NO"	NUMBER		NOT NULL,
	"DAY_OF_WEEK"	NUMBER		NOT NULL,
	"LECTURE_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LECTURE_DAYS"."LECTURE_DAYS_NO" IS '강의요일기본키(PK)';

COMMENT ON COLUMN "LECTURE_DAYS"."DAY_OF_WEEK" IS '월요일에서 일요일 숫자';

COMMENT ON COLUMN "LECTURE_DAYS"."LECTURE_NO" IS '강의번호(FK)';

CREATE TABLE "LECTURE_REVIEW" (
	"LECTURE_REVIEW_NO"	NUMBER		NOT NULL,
	"REVIEW_CONTENT"	VARCHAR2(500)		NOT NULL,
	"REVIEW_IMG"	VARCHAR2(300)		NULL,
	"CREATE_DATE_REVIEW"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(2)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"LECTURE_NO"	NUMBER		NOT NULL,
	"PARENT_REVIEW_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LECTURE_REVIEW"."LECTURE_REVIEW_NO" IS '강의후기번호(PK)';

COMMENT ON COLUMN "LECTURE_REVIEW"."REVIEW_CONTENT" IS '후기내용';

COMMENT ON COLUMN "LECTURE_REVIEW"."REVIEW_IMG" IS '후기이미지';

COMMENT ON COLUMN "LECTURE_REVIEW"."CREATE_DATE_REVIEW" IS '후기작성일';

COMMENT ON COLUMN "LECTURE_REVIEW"."COMMENT_DEL_FL" IS '댓글 삭제 여부(Y/N)';

COMMENT ON COLUMN "LECTURE_REVIEW"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "LECTURE_REVIEW"."LECTURE_NO" IS '강의번호(FK)';

COMMENT ON COLUMN "LECTURE_REVIEW"."PARENT_REVIEW_NO" IS '부모댓글번호';

CREATE TABLE "LECTURE" (
	"LECTURE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NULL,
	"LECTURE_CATEGORY_NUM"	NUMBER		NOT NULL,
	"LECTURE_HOME_TITLE"	VARCHAR2(300)		NOT NULL,
	"LECTURE_HOME_CONTENT"	VARCHAR2(300)		NOT NULL,
	"LECTURE_TITLE"	VARCHAR2(300)		NOT NULL,
	"LECTURE_CONTENT"	CLOB		NOT NULL,
	"PRICE"	NUMBER	DEFAULT 0	NOT NULL,
	"INSTRUCTOR_INTRODUCTION"	VARCHAR2(300)		NOT NULL,
	"LECTURE_LEVEL"	NUMBER		NOT NULL,
	"START_TIME"	NVARCHAR2(8)		NOT NULL,
	"HOW_LONG"	NUMBER		NOT NULL,
	"ACCEPTABLE_NUMBER"	NUMBER		NOT NULL,
	"REST_NUMBER"	NUMBER		NOT NULL,
	"START_DATE"	DATE		NOT NULL,
	"END_DATE"	DATE		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"LECTURE_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL
);

CREATE TABLE "LECTURE_TYPE" (
	"LECTURE_CATEGORY_NUM" NUMBER NOT NULL,
	"CATEGORY_NAME" NVARCHAR2(30) NOT NULL
);




COMMIT;

COMMENT ON COLUMN "LECTURE"."LECTURE_NO" IS '강의번호(PK)';

COMMENT ON COLUMN "LECTURE"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "LECTURE"."LECTURE_CATEGORY_NUM" IS '강의분류';

COMMENT ON COLUMN "LECTURE"."LECTURE_HOME_TITLE" IS '홈화면강의제목';

COMMENT ON COLUMN "LECTURE"."LECTURE_HOME_CONTENT" IS '홈화면강의내용';

COMMENT ON COLUMN "LECTURE"."LECTURE_TITLE" IS '강의상세보기제목';

COMMENT ON COLUMN "LECTURE"."LECTURE_CONTENT" IS '강의상세보기내용';

COMMENT ON COLUMN "LECTURE"."PRICE" IS '강의가격';

COMMENT ON COLUMN "LECTURE"."INSTRUCTOR_INTRODUCTION" IS '강사소개';

COMMENT ON COLUMN "LECTURE"."LECTURE_LEVEL" IS '초급:1,중급:2,고급:3';

COMMENT ON COLUMN "LECTURE"."START_TIME" IS '강의시작시간';

COMMENT ON COLUMN "LECTURE"."HOW_LONG" IS '강의끝나는시간';

COMMENT ON COLUMN "LECTURE"."ACCEPTABLE_NUMBER" IS '수용가능인원';

COMMENT ON COLUMN "LECTURE"."REST_NUMBER" IS '현재 남은 자리';

COMMENT ON COLUMN "LECTURE"."START_DATE" IS '강의시작날짜';

COMMENT ON COLUMN "LECTURE"."END_DATE" IS '강의종료날짜';

COMMENT ON COLUMN "LECTURE"."ENROLL_DATE" IS '강의등록날짜';

COMMENT ON COLUMN "LECTURE"."LECTURE_DEL_FL" IS '강의삭제여부(Y/N)';

CREATE TABLE "LECTURE_FILE" (
	"LECTURE_FILE_NO"	NUMBER		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NULL,
	"ORIGINAL_NAME"	VARCHAR2(300)		NULL,
	"FILE_RENAME"	VARCHAR2(100)		NULL,
	"UPLOAD_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"LECTURE_NO"	NUMBER		NOT NULL
);

CREATE TABLE "LECTURE_FILE"(
   "LECTURE_FILE_NO"     NUMBER CONSTRAINT "LECTURE_FILE_PK" PRIMARY KEY, -- 기본
   "LECTURE_NO"    NUMBER, -- 어떤 강의에 속한 이미지인지를 나타냄.
   "FILE_PATH"    VARCHAR2(500),
   "ORIGINAL_NAME" VARCHAR2(300),
   "FILE_RENAME"       VARCHAR2(100),
   "UPLOAD_DATE"    DATE DEFAULT SYSDATE,
   -- 외래키 제약조건
   CONSTRAINT "LECTURE_FILE_FK" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);

COMMIT;

COMMENT ON COLUMN "LECTURE_FILE"."LECTURE_FILE_NO" IS '강의파일번호';

COMMENT ON COLUMN "LECTURE_FILE"."FILE_PATH" IS '파일경로';

COMMENT ON COLUMN "LECTURE_FILE"."ORIGINAL_NAME" IS '원본파일명';

COMMENT ON COLUMN "LECTURE_FILE"."FILE_RENAME" IS '파일변경명';

COMMENT ON COLUMN "LECTURE_FILE"."UPLOAD_DATE" IS '파일등록일';

COMMENT ON COLUMN "LECTURE_FILE"."LECTURE_NO" IS '강의번호(FK)';

COMMENT ON COLUMN "LECTURE_FILE"."LECTURE_NO2" IS '강의번호(PK)';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	NVARCHAR2(100)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"BOARD_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_UPDATE_DATE"	DATE		NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글번호(PK)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."BOARD_WRITE_DATE" IS '게시글 작성일';

COMMENT ON COLUMN "BOARD"."BOARD_UPDATE_DATE" IS '게시글 마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_DEL_FL" IS '게시글삭제여부(Y/N)';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '작성한 회원번호(FK)';

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_PATH"	VARCHAR2(200)		NOT NULL,
	"IMG_ORIGINAL_NAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_RENAME"	NVARCHAR2(50)		NOT NULL,
	"IMG_ORDER"	NUMBER		NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지번호(PK)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_PATH" IS '이미지 요청 경로';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL_NAME" IS '이미지 원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '이미지 변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORDER" IS '이미지 순서';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글번호(FK)';

CREATE TABLE "BOARD_LIKE" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_LIKE"."MEMBER_NO" IS '회원번호(PFK)';

COMMENT ON COLUMN "BOARD_LIKE"."BOARD_NO" IS '게시글번호(PFK)';

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PARENT_COMMENT"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NO" IS '댓글 번호(PK)';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "COMMENT"."COMMENT_WRITE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "COMMENT"."COMMENT_DEL_FL" IS '댓글 삭제 여부(Y/N)';

COMMENT ON COLUMN "COMMENT"."PARENT_COMENT" IS '부모 댓글 번호';

COMMENT ON COLUMN "COMMENT"."MEMBER_NO" IS '회원번호(FK)';

COMMENT ON COLUMN "COMMENT"."BOARD_NO" IS '게시글번호(FK)';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "AUTH_KEY" ADD CONSTRAINT "PK_AUTH_KEY" PRIMARY KEY (
	"KEY_NO"
);

ALTER TABLE "LECTURE_DAYS" ADD CONSTRAINT "PK_LECTURE_DAYS" PRIMARY KEY (
	"LECTURE_DAYS_NO"
);

ALTER TABLE "LECTURE_REVIEW" ADD CONSTRAINT "PK_LECTURE_REVIEW" PRIMARY KEY (
	"LECTURE_REVIEW_NO"
);

ALTER TABLE "LECTURE" ADD CONSTRAINT "PK_LECTURE" PRIMARY KEY (
	"LECTURE_NO"
);

ALTER TABLE "LECTURE_TYPE" ADD CONSTRAINT "PK_LECTURE_TYPE" PRIMARY KEY (
	"LECTURE_CATEGORY_NUM"
);

ALTER TABLE "LECTURE_FILE" ADD CONSTRAINT "PK_LECTURE_FILE" PRIMARY KEY (
	"LECTURE_FILE_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE LECTURE ADD CONSTRAINT LECTURE_CATEGORY_NUM
FOREIGN KEY(LECTURE_CATEGORY_NUM) REFERENCES LECTURE_TYPE;

COMMIT;



---------------------- CHECK -----------------------

-- 게시글 삭제 여부
ALTER TABLE "BOARD" ADD
CONSTRAINT "BOARD_DEL_CHECK"
CHECK("BOARD_DEL_FL" IN ('Y', 'N') );

-- 댓글 삭제 여부
ALTER TABLE "COMMENT" ADD
CONSTRAINT "COMMENT_DEL_CHECK"
CHECK("COMMENT_DEL_FL" IN ('Y', 'N') );

-------------------------------------------------------
/* 게시글 번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE;

CREATE SEQUENCE SEQ_LECTURE_CATEGORY_NUM NOCACHE;


/* 게시판(BOARD) 테이블 샘플 데이터 삽입(PL/SQL)*/


SELECT * FROM "MEMBER";

SELECT * FROM BOARD;

-- DBMS_RANDOM.VALUE(0,3) : 0.0 이상, 3.0 미만의 난수
-- CEIL( DBMS_RANDOM.VALUE(0,3) ) : 1,2,3 중 하나

-- ALT + X 로 실행
BEGIN
	FOR I IN 1..2000 LOOP
		
		INSERT INTO "BOARD"
		VALUES(SEQ_BOARD_NO.NEXTVAL,
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글',
					 SEQ_BOARD_NO.CURRVAL || '번째 게시글 내용 입니다',
					 DEFAULT, DEFAULT, DEFAULT, DEFAULT,
					 1 -- MEMBER_NO(작성회원번호)
		);
		
	END LOOP;
END;

COMMIT;

-- 게시판 종류별 샘플 데이터 삽입 확인
SELECT COUNT(*)
FROM "BOARD";

-- 부모 댓글 번호 NULL 허용
ALTER TABLE "COMMENT" 
MODIFY PARENT_COMMENT NUMBER NULL;

/* 댓글 번호 시퀀스 생성 */
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE;

/* 댓글 ("COMMNET") 테이블에 샘플 데이터 추가 */

BEGIN
	FOR I IN 1..2000 LOOP
		INSERT INTO "COMMENT"	
		VALUES(
			SEQ_COMMENT_NO.NEXTVAL,
			SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			NULL, -- 부모댓글번호
			CEIL( DBMS_RANDOM.VALUE(0, 2000) ), -- 게시글번호
			2 -- 댓글작성회원번호
		);
	END LOOP;
END;

CREATE TABLE "COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"COMMENT_CONTENT"	NVARCHAR2(500)		NOT NULL,
	"COMMENT_WRITE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"COMMENT_DEL_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"PARENT_COMMENT"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

INSERT INTO "COMMENT" VALUES(SEQ_COMMENT_NO.NEXTVAL, SEQ_COMMENT_NO.CURRVAL || '번째 댓글 입니다',
			DEFAULT, DEFAULT,
			NULL,
			3,
			2000);

SELECT * FROM BOARD;

SELECT * FROM "MEMBER";

SELECT * FROM "COMMENT";

COMMIT;

/* BOARD_IMG 테이블용 시퀀스 생성 */
CREATE SEQUENCE SEQ_IMG_NO NOCACHE;

/* BOARD_IMG 테이블에 샘플 데이터 삽입 */
INSERT INTO "BOARD_IMG" VALUES(
	SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본1.jpg', 'test1.jpg', 0, 1950
);

INSERT INTO "BOARD_IMG" VALUES(
	SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본2.jpg', 'test2.jpg', 1, 1950
);

INSERT INTO "BOARD_IMG" VALUES(
	SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본3.jpg', 'test3.jpg', 2, 1950
);

INSERT INTO "BOARD_IMG" VALUES(
	SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본4.jpg', 'test4.jpg', 3, 1950
);

INSERT INTO "BOARD_IMG" VALUES(
	SEQ_IMG_NO.NEXTVAL, '/images/board/', '원본5.jpg', 'test5.jpg', 4, 1950
);

COMMIT;

SELECT * FROM BOARD_IMG;

/* 좋아요 테이블(BOARD_LIKE) 샘플 데이터 추가 */
INSERT INTO "BOARD_LIKE"
VALUES(1, 2000); -- 1번 회원이 1998번 글에 좋아요를 클릭함

COMMIT;

SELECT * FROM BOARD_LIKE;

CREATE TABLE "REGISTER_AUTH"(
   "REGISTER_AUTH_NO" NUMBER CONSTRAINT "REGISTER_AUTH_KEY" PRIMARY KEY,
   "MEMBER_NO" NUMBER NOT NULL,
   "AUTH_KEY" NVARCHAR2(4) NOT NULL,
   "PASS_FLAG" NUMBER NOT NULL, -- 통과하면 1 , 통과전엔 0 
   CONSTRAINT "REGISTER_AUTH_FK" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_REGISTER_AUTH_NO NOCACHE; 

SELECT * FROM REGISTER_AUTH;

COMMIT;

SELECT * FROM LECTURE_TYPE;

INSERT INTO LECTURE_TYPE VALUES (
SEQ_LECTURE_CATEGORY_NUM.NEXTVAL,
'비누'
);
INSERT INTO LECTURE_TYPE VALUES (
SEQ_LECTURE_CATEGORY_NUM.NEXTVAL,
'유리 공예'
);
INSERT INTO LECTURE_TYPE VALUES (
SEQ_LECTURE_CATEGORY_NUM.NEXTVAL,
'드로잉'
);
INSERT INTO LECTURE_TYPE VALUES (
SEQ_LECTURE_CATEGORY_NUM.NEXTVAL,
'가죽 공예'
);
INSERT INTO LECTURE_TYPE VALUES (
SEQ_LECTURE_CATEGORY_NUM.NEXTVAL,
'요리'
);

COMMIT;

INSERT INTO "LECTURE"
VALUES(SEQ_LECTURE_NO.NEXTVAL, -- LECTURE_NO
          1, -- MEMBER_NO
          1, -- 1은 향수를 나타냄. 
          '비누비누비누', -- LECTURE_NAME
          '향기로 자신을 나타내보시는게 어떠신가요..?', -- LECTURE_TITLE 
          '향기를 배우는 수업',
          '향수를 어떻게 배우는지 과정이 궁금하시지 않으셨나요? 실제로 향수를 만들어보면서 어떤 향기가 자신에게 어울리는지, 자신을 알아가는 시간을 가져봐요!', -- LECTURE_CONTENT
          30000, -- PRICE
          '안녕하세요 강사 최재준입니다. 저는 어쩌구저쩌구 갈릴레오 알리오올리오', -- INSTRUCTOR INTRODUCTION
          1, -- 레벨 초급 중급 고급
          1030, -- 강의 시작 시각
          2, -- 강의 지속 시간
          15, -- 수용가능인원
          13, -- 남은자리
          TO_DATE('2024-04-01', 'YYYY-MM-DD'), -- 강의 시작 날짜
          TO_DATE('2024-04-15', 'YYYY-MM-DD'), -- 강의 종료 날짜
          DEFAULT, -- 강의 등록 날짜6
          DEFAULT -- 강의를 삭제했는지 여부
);

INSERT INTO "LECTURE"
VALUES(SEQ_LECTURE_NO.NEXTVAL, -- LECTURE_NO
          3, -- MEMBER_NO
          2, -- 1은 향수를 나타냄. 
          '유리', -- LECTURE_NAME
          '향기로 자신을 나타내보시는게 어떠신가요..?', -- LECTURE_TITLE 
          '향기를 배우는 수업',
          '향수를 어떻게 배우는지 과정이 궁금하시지 않으셨나요? 실제로 향수를 만들어보면서 어떤 향기가 자신에게 어울리는지, 자신을 알아가는 시간을 가져봐요!', -- LECTURE_CONTENT
          30000, -- PRICE
          '안녕하세요 강사 최재준입니다. 저는 어쩌구저쩌구 갈릴레오 알리오올리오', -- INSTRUCTOR INTRODUCTION
          1, -- 레벨 초급 중급 고급
          1030, -- 강의 시작 시각
          2, -- 강의 지속 시간
          15, -- 수용가능인원
          13, -- 남은자리
          TO_DATE('2024-04-01', 'YYYY-MM-DD'), -- 강의 시작 날짜
          TO_DATE('2024-04-15', 'YYYY-MM-DD'), -- 강의 종료 날짜
          DEFAULT, -- 강의 등록 날짜6
          DEFAULT -- 강의를 삭제했는지 여부
);

INSERT INTO "LECTURE"
VALUES(SEQ_LECTURE_NO.NEXTVAL, -- LECTURE_NO
          4, -- MEMBER_NO
          3, -- 1은 향수를 나타냄. 
          '드!로!잉!', -- LECTURE_NAME
          '향기로 자신을 나타내보시는게 어떠신가요..?', -- LECTURE_TITLE 
          '향기를 배우는 수업',
          '향수를 어떻게 배우는지 과정이 궁금하시지 않으셨나요? 실제로 향수를 만들어보면서 어떤 향기가 자신에게 어울리는지, 자신을 알아가는 시간을 가져봐요!', -- LECTURE_CONTENT
          30000, -- PRICE
          '안녕하세요 강사 최재준입니다. 저는 어쩌구저쩌구 갈릴레오 알리오올리오', -- INSTRUCTOR INTRODUCTION
          1, -- 레벨 초급 중급 고급
          1030, -- 강의 시작 시각
          2, -- 강의 지속 시간
          15, -- 수용가능인원
          13, -- 남은자리
          TO_DATE('2024-04-01', 'YYYY-MM-DD'), -- 강의 시작 날짜
          TO_DATE('2024-04-15', 'YYYY-MM-DD'), -- 강의 종료 날짜
          DEFAULT, -- 강의 등록 날짜6
          DEFAULT -- 강의를 삭제했는지 여부
);

INSERT INTO "LECTURE"
VALUES(SEQ_LECTURE_NO.NEXTVAL, -- LECTURE_NO
          1, -- MEMBER_NO
          4, -- 1은 향수를 나타냄. 
          '가죽이잖아', -- LECTURE_NAME
          '향기로 자신을 나타내보시는게 어떠신가요..?', -- LECTURE_TITLE 
          '향기를 배우는 수업',
          '향수를 어떻게 배우는지 과정이 궁금하시지 않으셨나요? 실제로 향수를 만들어보면서 어떤 향기가 자신에게 어울리는지, 자신을 알아가는 시간을 가져봐요!', -- LECTURE_CONTENT
          30000, -- PRICE
          '안녕하세요 강사 최재준입니다. 저는 어쩌구저쩌구 갈릴레오 알리오올리오', -- INSTRUCTOR INTRODUCTION
          1, -- 레벨 초급 중급 고급
          1030, -- 강의 시작 시각
          2, -- 강의 지속 시간
          15, -- 수용가능인원
          13, -- 남은자리
          TO_DATE('2024-04-01', 'YYYY-MM-DD'), -- 강의 시작 날짜
          TO_DATE('2024-04-15', 'YYYY-MM-DD'), -- 강의 종료 날짜
          DEFAULT, -- 강의 등록 날짜6
          DEFAULT -- 강의를 삭제했는지 여부
);

INSERT INTO "LECTURE"
VALUES(SEQ_LECTURE_NO.NEXTVAL, -- LECTURE_NO
          1, -- MEMBER_NO
          5, -- 1은 향수를 나타냄. 
          '요리왕', -- LECTURE_NAME
          '향기로 자신을 나타내보시는게 어떠신가요..?', -- LECTURE_TITLE 
          '향기를 배우는 수업',
          '향수를 어떻게 배우는지 과정이 궁금하시지 않으셨나요? 실제로 향수를 만들어보면서 어떤 향기가 자신에게 어울리는지, 자신을 알아가는 시간을 가져봐요!', -- LECTURE_CONTENT
          30000, -- PRICE
          '안녕하세요 강사 최재준입니다. 저는 어쩌구저쩌구 갈릴레오 알리오올리오', -- INSTRUCTOR INTRODUCTION
          1, -- 레벨 초급 중급 고급
          1030, -- 강의 시작 시각
          2, -- 강의 지속 시간
          15, -- 수용가능인원
          13, -- 남은자리
          TO_DATE('2024-04-01', 'YYYY-MM-DD'), -- 강의 시작 날짜
          TO_DATE('2024-04-15', 'YYYY-MM-DD'), -- 강의 종료 날짜
          DEFAULT, -- 강의 등록 날짜6
          DEFAULT -- 강의를 삭제했는지 여부
);

COMMIT;

SELECT * FROM LECTURE_TYPE;

SELECT * FROM LECTURE;

SELECT COUNT(*) FROM LECTURE;

SELECT COUNT(*) FROM LECTURE WHERE LECTURE_CATEGORY_NUM = 1; 

	    SELECT
	        L.LECTURE_NO,
	        L.MEMBER_NO,
	        L.LECTURE_CATEGORY_NUM,
	        L.LECTURE_HOME_TITLE,
	        L.LECTURE_HOME_CONTENT,
	        L.PRICE,
	        L.LECTURE_LEVEL,
     	    TO_CHAR(L.START_DATE, 'YYYY-MM-DD') FORMMATED_START_DATE,
	        TO_CHAR(L.END_DATE, 'YYYY-MM-DD') FORMMATED_END_DATE,	 
  
			
			LF.LECTURE_FILE_NO,
			LF.FILE_PATH,
			LF.ORIGINAL_NAME,
			LF.FILE_RENAME,
			
			M.MEMBER_NICKNAME,
	        M.PROFILE_IMG
			
			
			FROM LECTURE L
			LEFT JOIN LECTURE_FILE LF ON L.LECTURE_NO = LF.LECTURE_NO
			LEFT JOIN MEMBER M ON L.MEMBER_NO = M.MEMBER_NO
			WHERE LECTURE_CATEGORY_NUM = 1
			ORDER BY L.ENROLL_DATE DESC;

CREATE TABLE "LECTURE_ADDRESS"(
   "LECTURE_ADDRESS_NO" NUMBER CONSTRAINT "LECTURE_ADDRESS_KEY" PRIMARY KEY,
   "MEMBER_NO" NUMBER,
   "LECTURE_NO" NUMBER, 
   "POST_CODE" NVARCHAR2(30),
   "ROAD_ADDRESS" NVARCHAR2(30),
   "JIBUN_ADDRESS" NVARCHAR2(30),
   "DETAIL_ADDRESS" NVARCHAR2(100),
   CONSTRAINT "LECTURE_ADDRESS_FK_1" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE,
   CONSTRAINT "LECTURE_ADDRESS_FK_2" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);

SELECT * FROM LECTURE;

SELECT * FROM "MEMBER";

COMMIT;

SELECT * FROM LECTURE_ADDRESS;

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	1,
	13,
	12345,
	'서울시',
	'지번',
	'상세주소'
);



INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	2,
	14,
	12345,
	'서울시',
	'지번',
	'상세주소'
);

COMMIT;

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	3,
	15,
	12345,
	'강원도',
	'지번',
	'상세주소'
);

SELECT * FROM "MEMBER";

SELECT * FROM "COMMENT";

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	4,
	16,
	12345,
	'충청남도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	1,
	17,
	12345,
	'경상북도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	2,
	18,
	12345,
	'경상남도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	3,
	19,
	12345,
	'전라북도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	4,
	20,
	12345,
	'전라남도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	1,
	21,
	12345,
	'제주시',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	2,
	22,
	12345,
	'제주특별시',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	3,
	23,
	12345,
	'경기도',
	'지번',
	'상세주소'
);

INSERT INTO LECTURE_ADDRESS
VALUES(
	SEQ_LECTURE_ADDRESS_NO.NEXTVAL,
	4,
	24,
	12345,
	'충청북도',
	'지번',
	'상세주소'
);

CREATE SEQUENCE SEQ_LECTURE_ADDRESS_NO NOCACHE;
COMMIT;
SELECT * FROM LECTURE_ADDRESS;
SELECT * FROM LECTURE;

CREATE TABLE "LECTURE_MAP"(
   "LECTURE_MAP_NO" NUMBER CONSTRAINT "LECTURE_MAP_KEY" PRIMARY KEY,
   "LECTURE_NO" NUMBER, 
   "LATITUDE" NVARCHAR2(300),
   "HARDNESS" NVARCHAR2(300),
   CONSTRAINT "LECTURE_MAP_FK" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);

--------------------------------------------------------

-- 여기서부터 확인

--===============================================================================================================

-- 결제 ORDERS 테이블이다. 
CREATE TABLE "LECTURE_ORDERS"(
   "LECTURE_ORDERS_NO" NUMBER CONSTRAINT "LECTURE_ORDERS_KEY" PRIMARY KEY,
   "MEMBER_NO" NUMBER, 
   "LECTURE_NO" NUMBER,
   "MERCHANT_UID" VARCHAR2(300),
   "AMOUNT" NUMBER,
   "QUANTITY" NUMBER,
   "STATUS" VARCHAR2(300),
   "FAIL_REASON" VARCHAR2(300),
   "CREATED" DATE,
   CONSTRAINT "LECTURE_ORDERS_FK_1" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE,
   CONSTRAINT "LECTURE_ORDERS_FK_2" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_LECTURE_ORDERS_NO NOCACHE;

DROP TABLE LECTURE_ORDERS;

INSERT INTO LECTURE_ORDERS VALUES
(
SEQ_LECTURE_ORDERS_NO.NEXTVAL,
1,
8,
'pid-1714993047682',
3,
3,
'PAID',
NULL,
SYSDATE
);

SELECT * FROM LECTURE;

COMMIT;

SELECT * FROM LECTURE_ORDERS;


DROP TABLE LECTURE_PAYMENTS;

--==================================================================================================================
-- 결제 PAYMENT 테이블이다. 
CREATE TABLE "LECTURE_PAYMENTS" (
   "LECTURE_PAYMENTS_NO" NUMBER CONSTRAINT "LECTURE_PAYMENTS_KEY" PRIMARY KEY,
   
   "MEMBER_NO" NUMBER,
   "LECTURE_ORDERS_NO" NUMBER,
   "IMP_UID" VARCHAR2(300),
   "MERCHANT_UID" VARCHAR2(300),
   "AMOUNT" NUMBER, 
   
   "CURRENCY" VARCHAR2(300),
   "STATUS" VARCHAR2(300),
   "FAIL_REASON" VARCHAR2(300),
   "FAILD_AT" DATE,
   "PAY_METHOD" VARCHAR2(300),
   
   "NAME" VARCHAR2(300),
   "PAID_AT" DATE,
   "RECEIPT_URL" VARCHAR2(300),
   "STARTED_AT" DATE,
   "USER_AGENT" VARCHAR2(300),
   
   "BUYER_NAME" VARCHAR2(300),
   "BUYER_TEL" VARCHAR2(300),
   "BUYER_ADDR" VARCHAR2(300),
   "BUYER_POSTCODE" VARCHAR2(300),
   "BUYER_EMAIL" VARCHAR2(300),
   
   "APPLY_NUM" VARCHAR2(300),
   "CARD_CODE" VARCHAR2(300),
   "CARD_NAME" VARCHAR2(300),
   "CARD_NUMBER" VARCHAR2(300),
   "CARD_QUOTA" NUMBER, 
   
   "CARD_TYPE" NUMBER, 
   "BANK_CODE" VARCHAR2(300),
   "BANK_NAME" VARCHAR2(300),
   "VBANK_CODE" VARCHAR2(300),
   "VBANK_DATE" NUMBER,
   
   "VBANK_HOLDER" VARCHAR2(300),
   "VBANK_ISSUED_AT" DATE,
   "VBANK_NUM" VARCHAR2(300),
   "VBANK_NAME" VARCHAR2(300),
   "CUSTOM_DATA" VARCHAR2(300),
   
   "CUSTOMER_UID" VARCHAR2(300),
   "CUSTOMER_UID_USAGE" VARCHAR2(300),
   "CHANNEL" VARCHAR2(300),
   "CASH_RECEIPT_ISSUED" VARCHAR2(300),
   "ESCROW" VARCHAR2(300),
   
   "PG_ID" VARCHAR2(300),
   "PG_PROVIDER" VARCHAR2(300),
   "EMB_PG_PROVIDER" VARCHAR2(300),
   "PG_TID" VARCHAR2(300),
   "CANCEL_AMOUNT" NUMBER,
   
   "CANCEL_REASON" VARCHAR2(300),
   "CANCELLD_AT" VARCHAR2(300)   ,
   
   CONSTRAINT "LECTURE_PAYMENTS_FK_1" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE,
   CONSTRAINT "LECTURE_PAYMENTS_FK_2" FOREIGN KEY ("LECTURE_ORDERS_NO") REFERENCES "LECTURE_ORDERS"("LECTURE_ORDERS_NO") ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_LECTURE_PAYMENTS_NO NOCACHE;

COMMIT;
SELECT * FROM lecture_payments;




------------------------------------=============================================================
CREATE TABLE "LECTURE_RESTNUM"(
   "LECTURE_RESTNUM_NO" NUMBER CONSTRAINT "LECTURE_RESTNUM_PK" PRIMARY KEY, -- 기본
   "LECTURE_NO"    NUMBER, -- 어떤 강의에 속한 이미지인지를 나타냄.
   "LECTURE_DATE" DATE,
   "REST_NUM"    NUMBER,

   -- 외래키 제약조건
   CONSTRAINT "LECTURE_RESTNUM_FK" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);
DROP TABLE LECTURE_RESTNUM;



CREATE SEQUENCE SEQ_LECTURE_RESTNUM_NO NOCACHE;

COMMIT;

SELECT * FROM LECTURE_RESTNUM;


SELECT * FROM LECTURE_RESTNUM WHERE LECTURE_NO = 306;

SELECT * FROM LECTURE_ORDERS;
SELECT * FROM LECTURE_PAYMENTS;

--------------------------------------------------------------------------------------------
-- 누가 어떤 강의의 어떤 날짜에 강의 등록을 했냐?  를 나타내는 테이블임. 
-- 만약, 강사가 특정인물을 강의등록에서 배제할 시 이 테이블에서는 삭제(실제로 삭제하지는 말고 FL 만 Y 로). 그리고, 환불대상 목록을 나타내는 테이블에 그 이름을 올려야해. 
CREATE TABLE "REGISTERED_MEMBER"(
   "REGISTERED_MEMBER_NO" NUMBER CONSTRAINT "REGISTERED_MEMBER_PK" PRIMARY KEY, -- 기본
   "MEMBER_NO"    NUMBER, 
   "LECTURE_NO" NUMBER,
   "LECTURE_DATE"    DATE,
   "MERCHANT_UID" VARCHAR2(300),
   "REGISTERED_MEMBER_FL" CHAR(1) DEFAULT 'N',

   -- 외래키 제약조건
   CONSTRAINT "REGISTERED_MEMBER_FK_1" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE,
   CONSTRAINT "REGISTERED_MEMBER_FK_2" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE
);



DROP TABLE REGISTERED_MEMBER;

SELECT * FROM REGISTERED_MEMBER;

UPDATE REGISTERED_MEMBER 
SET REGISTERED_MEMBER_FL = 'N';
SELECT * FROM REGISTERED_MEMBER;
COMMIT;

SELECT * FROM LECTURE
WHERE LECTURE_NO = 297;
SELECT * FROM lecture_restnum; WHERE lecture_no = 297; 
AND lecture_date = to_date('2024-05-17', 'YYYY-MM-DD');


CREATE SEQUENCE SEQ_REGISTERED_MEMBER_NO NOCACHE;

SELECT * FROM REGISTERED_MEMBER;
DELETE FROM REGISTERED_MEMBER WHERE REGISTERED_MEMBER_NO = 1;
COMMIT;

COMMIT;

SELECT RM.*, M.*
FROM REGISTERED_MEMBER RM 
LEFT JOIN MEMBER M ON RM.MEMBER_NO = M.MEMBER_NO
WHERE LECTURE_NO = 307;


SELECT * FROM REGISTERED_MEMBER;






SELECT
    L.LECTURE_DATE,
    M.MEMBER_NICKNAME,
    M.PROFILE_IMG,
    L.REST_NUM
FROM
    LECTURE_RESTNUM L
    LEFT JOIN REGISTERED_MEMBER R ON L.LECTURE_NO = R.LECTURE_NO AND L.LECTURE_DATE = R.LECTURE_DATE
    LEFT JOIN MEMBER M ON R.MEMBER_NO = M.MEMBER_NO
WHERE
    L.LECTURE_NO = 307  -- Use the specific lecture number here
ORDER BY
    L.LECTURE_DATE;


   
--========================================================================================================
;
--강의료 정산과 관련된 테이블
CREATE TABLE "FEE_SETTLEMENT"(
   "FEE_SETTLEMENT_NO"       NUMBER CONSTRAINT "FEE_SETTLEMENT_PK" PRIMARY KEY,
   "LECTURER_MEMBER_NO"       NUMBER  NOT NULL,
   "SETTLEMENT_AMOUNT"         NUMBER NOT NULL,
   CONSTRAINT "FEE_SETTLEMENT_FK" FOREIGN KEY ("LECTURER_MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FEE_SETTLEMENT_NO NOCACHE;

SELECT * FROM FEE_SETTLEMENT;

--=======================================================================================================================

-- 환불해줘야 할 고객
CREATE TABLE "REFUND_CUSTOMER"(
   "REFUND_CUSTOMER_NO" NUMBER CONSTRAINT "REFUND_CUSTOMER_PK" PRIMARY KEY,
   "LECTURE_NO" NUMBER,
   "MERCHANT_UID" VARCHAR2(300),
   "REFUND_CUSTOMER_MEMBER_NO"       NUMBER  NOT NULL,
   "REFUND_AMOUNT"         NUMBER NOT NULL,
   "REFUND_REASON" VARCHAR2(300),
   "REFUND_STATUS" VARCHAR2(300) NOT NULL,
   "REFUND_REQUEST_DATE" DATE,
   "REFUND_PROCESSING_DATE" DATE,
   CONSTRAINT "REFUND_CUSTOMER_FK_1" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE,
   CONSTRAINT "REFUND_CUSTOMER_FK_2" FOREIGN KEY ("REFUND_CUSTOMER_MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE
);
CREATE SEQUENCE SEQ_REFUND_CUSTOMER_NO NOCACHE;
COMMIT;
SELECT * FROM REFUND_CUSTOMER;

SELECT * FROM LECTURE;

INSERT INTO REFUND_CUSTOMER VALUES(
   SEQ_REFUND_CUSTOMER_NO.NEXTVAL,
   307,
   'pid-1715003440205',
   20,
   3,
   '강사가 강의 취소함!',
   'NOT REFUND',
   SYSDATE,
   SYSDATE
);

SELECT * FROM LECTURE_REVIEW;

CREATE SEQUENCE SEQ_LECTURE_NO NOCACHE;

CREATE SEQUENCE SEQ_LECTURE_MAP_NO NOCACHE;

COMMIT;

CREATE TABLE "LECTURE_REVIEW" (
   "LECTURE_REVIEW_NO" NUMBER CONSTRAINT "LECTURE_REVIEW_PK" PRIMARY KEY,
   "MEMBER_NO" NUMBER, --누가
   "LECTURE_NO" NUMBER, --어떤 강의에
   "REVIEW_CONTENT" VARCHAR2(500), -- 뭐라고 남겼냐?
   "REVIEW_IMG" VARCHAR2(300),    -- 사진 하나만 첨부하게 해줄거임. 
   "CREATE_DATE_REVIEW" DATE DEFAULT SYSDATE, -- 생성시점
   "PARENT_REVIEW_NO" NUMBER, -- 부모 후기의 LECTURE_REVIEW_NO 값. 대댓글을 표현하기 위함임.
   "REVIEW_DEL_FL" CHAR(1) DEFAULT 'N' CHECK("REVIEW_DEL_FL" IN ('Y', 'N')), -- 삭제됬는지 여부. 강의와 상관없이 후기가 존재하는지 체크할 필요가 있어서 넣음. 
   
   -- 외래키 제약조건
   CONSTRAINT "LECTURE_REVIEW_FK_1" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER"("MEMBER_NO") ON DELETE CASCADE,--어차피, MEMBER 테이블 행 지워지면, LECTURE 도 지워지도록 해놨음. 
   CONSTRAINT "LECTURE_REVIEW_FK_2" FOREIGN KEY ("LECTURE_NO") REFERENCES "LECTURE"("LECTURE_NO") ON DELETE CASCADE 
);