SELECT * FROM RESERVE_INFO;

SELECT * FROM MEETING_ROOM;

ALTER TABLE RESERVE_INFO ADD COM_NO NUMBER;

DELETE FROM RESERVE_INFO WHERE RESERVE_INFO_NO = 11;

COMMIT;

ALTER TABLE RESERVE_INFO RENAME COLUMN TEAM_RESERVE TO TEAM_SHARE;
ALTER TABLE RESERVE_INFO RENAME COLUMN DEPT_RESERVE TO DEPT_SHARE;
ALTER TABLE RESERVE_INFO RENAME COLUMN COM_RESERVE TO COM_SHARE;

UPDATE RESERVE_INFO SET COM_NO = 9 WHERE RESERVE_INFO_NO = 7;

SELECT RESERVE_INFO_TITLE, RESERVE_INFO_START, RESERVE_INFO_END, RESERVE_INFO_COLOR, EMP_CODE,
			TEAM_SHARE, DEPT_SHARE, COM_SHARE, MEETING_ROOM_NO, COM_NO
FROM RESERVE_INFO
WHERE COM_NO = 9;

SELECT 
    r.RESERVE_INFO_TITLE, 
    r.RESERVE_INFO_START, 
    r.RESERVE_INFO_END, 
    r.RESERVE_INFO_COLOR, 
    r.EMP_CODE,
    r.TEAM_RESERVE, 
    r.DEPT_RESERVE, 
    r.COM_RESERVE, 
    r.MEETING_ROOM_NO, 
    r.COM_NO,
    m.MEETING_ROOM_NM
FROM 
    RESERVE_INFO r
JOIN 
    MEETING_ROOM m ON r.MEETING_ROOM_NO = m.MEETING_ROOM_NO
WHERE 
    r.COM_NO = 9;
    
SELECT * FROM DEPARTMENT;
SELECT * FROM TEAM;

SELECT COUNT(*)
FROM RESERVE_INFO
WHERE MEETING_ROOM_NO = 8
AND '2024-06-12T21:30:00.000Z' < RESERVE_INFO_END
AND '2024-06-12T24:30:00.000Z' > RESERVE_INFO_START;


SELECT * 
